### ISSUE TITLE
Finish creating R package

### ISSUE THREAD

**Issue by jaeddy** [Sage-Bionetworks/syndccutils#31]
Most of the pieces are in place, but needs some additional steps and cleanup to turn into an actual (*installable*) R package. As we complete this process, that'd also be a good time to change the name re: #29.

I'd welcome input from folks who have built R packages before to figure out what specific steps are left...

**note:** we won't worry about the Python code for now

**Comment by sgosline** [comment]
This includes moving all R-related stuff into the R directory.

**Comment by jaeddy** [comment]
Clarifying @sgosline's comment: the GH repo would be the home for both an R and Python package (for as long as we think there might be a need for both). Besides some high level information, the idea would be for the `R` folder to be a self-contained R package (including it's own `R` subfolder, `DESCRIPTION`, etc.).

**Comment by karawoo** [comment]
> I'd welcome input from folks who have built R packages before to figure out what specific steps are left...

From a quick pass here are some specific steps I see that are needed (there may be more):

- [ ] Remove remaining calls to `library()` e.g. in `charts.R` and make sure all packages are listed as dependencies.
  - [ ] I don't think viridis is necessary, but we should have viridisLite
  - [ ] Some of the functionality uses the development version of ggplot2, so ggplot2 needs to be listed under Remotes in the DESCRIPTION
  - [ ] Figure out how to import synapser since it's not installable from either CRAN or GitHub
- [ ] Import commonly used functions into the package NAMESPACE. I think it probably makes sense to import all of ggplot2 and the most commonly used functions from purrr, dplyr, etc. This way we won't have to do so much `::`-ing.
- [ ] Replace `CSBCPSONPortal` with `syndccutils` in `testthat.R`
- [ ] List extra files/folders in `.Rbuildignore`
- [ ] Fill out DESCRIPTION title, description, authors
- [ ] Add a license
- [ ] Generate documentation files using roxygen2

Other things that it would be good to do at some point:

- Write more examples in function documentation
- Flesh out testing. We could use the vdiffr package to test the plotting functions, though my experience is that it's hard to get that working consistently across multiple contributors.
- Set up continuous integration with Travis-CI. This isn't too hard, but I've never done it with a package that makes API calls that require authentication. However it's really handy because it will show you if any changes you make break existing tests or package building rules.

I can start work on PRs to address some of the stuff in the first section.

**Comment by kdaily** [comment]
`synapser` should be able to be installed by setting a `REMOTE` to https://sage-bionetworks.github.io/ran - but may need to also include `PythonEmbedInR` explicitly as well. I don't think the `synapser` `DESCRIPTION` file has been modified to include that.

**Comment by kdaily** [comment]
Strike the above - we should be able to use an `Additional_repositories` in our `DESCRIPTION`. See discussion here: https://sagebionetworks.jira.com/browse/SYNR-1223

**Comment by karawoo** [comment]
👍 

And it looks like synapser does include PythonEmbedInR in its DESCRIPTION (actually both under Imports and Depends, which it probably shouldn't)

**Comment by jaeddy** [comment]
Thanks @karawoo! 

> Import commonly used functions into the package NAMESPACE. I think it probably makes sense to import all of ggplot2 and the most commonly used functions from purrr, dplyr, etc. This way we won't have to do so much ::-ing.

Good to know — I'm never sure what best practice is for `::` use, so I probably tend to go overboard.

Re: other things:

> Write more examples in function documentation

I have an R Notebook with examples of several functions. I'll try to get those incorporated to function docs soon (and maybe include the nb as a vignette for now) — this was also requested by @kdaily, for the sake of making it clear to *us* what various functions do.

> Flesh out testing. We could use the vdiffr package to test the plotting functions, though my experience is that it's hard to get that working consistently across multiple contributors.

If you take a look at #56, my goal is to separate as much of the pre-plotting data modification/formatting steps as possible. Testing dataframe outputs should be easier, and from there I'd mostly be OK with "trusting" the plotting functions.

> Set up continuous integration with Travis-CI. This isn't too hard, but I've never done it with a package that makes API calls that require authentication. However it's really handy because it will show you if any changes you make break existing tests or package building rules.

Agreed! Honestly, the `synapser` calls aren't used very much at this point other than to download/upload data. The Synapse clients should have examples of how we can mock authentication, but the `synapse_helpers` are probably lower priority for testing right now, and thus not a pre-requisite for Travis.

**Comment by karawoo** [comment]
I'm currently working on a PR to clean up the dependencies and NAMESPACE a bit, it may take a little while to make sure everything is sorted out correctly, but just putting a note here so you all know it's in progress.

**Comment by karawoo** [comment]
Another thing to do is:
- [ ] move `test_data.R` into a location that is `.Rbuildignore`-ed. 

Right now it's going to write out the files to the user's file system whenever the package is installed. Usually the place for scripts that generate data used by the package is in a `data-raw/` folder.

**Comment by jaeddy** [comment]
@karawoo / @kdaily — OK to close this? Successful build on Travis seems sufficient to me, but let me know if there are other issues to address.

**Comment by karawoo** [comment]
@jaeddy can I do a quick PR to change the [title](https://github.com/Sage-Bionetworks/syndccutils/blob/master/R/DESCRIPTION#L2) and [description](https://github.com/Sage-Bionetworks/syndccutils/blob/master/R/DESCRIPTION#L8) lines in the DESCRIPTION file, and thus check the last of the boxes? It's not needed for the package to work but would be satisfying 😄

**Comment by jaeddy** [comment]
Go for it!

**Comment by kdaily** [comment]
![check](https://media.giphy.com/media/11vMVw9d5MgcBW/giphy.gif)
