### ISSUE TITLE
ggplot2 dependency trouble

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/syndccutils#93]
`DESCRIPTION` requires ggplot2 2.2.1.9000; couldn't get this. Looks like this was maybe installed via `devtools`? Is it really required?

**Comment by kdaily** [comment]
Should have git blamed first, @karawoo added that. When I installed the package it complained. Will try again!

**Comment by karawoo** [comment]
It is needed because some functions in the package use ggplot2 functionality that's only in the development version (like the viridis scales). What error did you get? This line ought to ensure that you get the version from devtools:

https://github.com/Sage-Bionetworks/syndccutils/blob/c369f0a852aed0125997154a470e91a7dcc7ca61/R/DESCRIPTION#L43
